In [1]:
import pandas as pd

# 1. categories.csv

In [38]:
df1 = pd.read_csv("categories.csv")

In [39]:
# first few rows
df1.head()

       category_id category_name
0  sr:category:181    Hopman Cup
1    sr:category:3           ATP
2   sr:category:72    Challenger
3    sr:category:6           WTA
4   sr:category:76     Davis Cup

In [40]:
# rows and columns
df1.shape

(18, 2)

In [41]:
# dataset basic information
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   category_id    18 non-null     object
 1   category_name  18 non-null     object
dtypes: object(2)
memory usage: 416.0+ bytes

In [42]:
# Statistical information
df1.describe()

            category_id category_name
count                18            18
unique               18            18
top     sr:category:181    Hopman Cup
freq                  1             1

In [43]:
df1.isnull().sum()

category_id      0
category_name    0
dtype: int64

In [44]:
df1.duplicated().sum()

0

### Saving clean csv

In [45]:
df1.to_csv("clean_categories.csv", index = False)

### Loaded clean categories csv

In [46]:
clean_csv = pd.read_csv("clean_categories.csv")
clean_csv.head()

       category_id category_name
0  sr:category:181    Hopman Cup
1    sr:category:3           ATP
2   sr:category:72    Challenger
3    sr:category:6           WTA
4   sr:category:76     Davis Cup

###  # categories.csv is perfectly clean and ready for insights

# 2. competitions.csv

In [47]:
df2 = pd.read_csv("competitions.csv")

In [48]:
df2.head()

,competition_id,competition_name,type,gender,category_id,category_name
0,sr:competition:620,Hopman Cup,mixed,mixed,sr:category:181,Hopman Cup
1,sr:competition:660,World Team Cup,mixed,men,sr:category:3,ATP
2,sr:competition:990,ATP Challenger Tour Finals,singles,men,sr:category:72,Challenger
3,sr:competition:1207,Championship International Series,singles,women,sr:category:6,WTA
4,sr:competition:2100,Davis Cup,mixed,men,sr:category:76,Davis Cup

In [49]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6490 entries, 0 to 6489
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   competition_id    6490 non-null   object
 1   competition_name  6490 non-null   object
 2   type              6490 non-null   object
 3   gender            6488 non-null   object
 4   category_id       6490 non-null   object
 5   category_name     6490 non-null   object
dtypes: object(6)
memory usage: 304.3+ KB

In [50]:
df2.shape

(6490, 6)

In [51]:
df2.columns

Index(['competition_id', 'competition_name', 'type', 'gender', 'category_id',
       'category_name'],
      dtype='object')

In [52]:
df2.describe()

,competition_id,competition_name,type,gender,category_id,category_name
count,6490,6490,6490,6488,6490,6490
unique,6490,6490,4,3,18,18
top,sr:competition:620,Hopman Cup,singles,men,sr:category:785,ITF Men
freq,1,1,3475,3715,2198,2198

# Total count - 6490
# Gender showing 2 missing values - need to clean

In [53]:
df2['gender']

0       mixed
1         men
2         men
3       women
4         men
        ...
6485      men
6486    women
6487    women
6488    women
6489    women
Name: gender, Length: 6490, dtype: object

In [54]:
df2[df2['gender'].isnull()]

,competition_id,competition_name,type,gender,category_id,category_name
6376,sr:competition:49660,Battle of the Sexes,singles,NaN,sr:category:79,Exhibition
6389,sr:competition:49854,Miami Invitational,singles,NaN,sr:category:79,Exhibition

### Filling missing values in gender as 'Unknown'

In [56]:
df2['gender'].fillna('Unknown', inplace=True)

In [57]:
df2['gender']

0       mixed
1         men
2         men
3       women
4         men
        ...
6485      men
6486    women
6487    women
6488    women
6489    women
Name: gender, Length: 6490, dtype: object

In [58]:
# verify

df2['gender'].isnull().sum()

0

In [17]:
# Now no missing values in gender

In [59]:
df2.isnull().sum()

competition_id      0
competition_name    0
type                0
gender              0
category_id         0
category_name       0
dtype: int64

In [20]:
# No missing values in dataset.

# Need to remove the category_name column:
    
    1. Because it already exist in categories table
    2. by keeping in both csv shows data redundancy
    3. in sql, we need to join using category id

In [60]:
df2.columns

Index(['competition_id', 'competition_name', 'type', 'gender', 'category_id',
       'category_name'],
      dtype='object')

### Removing category_name column

In [61]:
df2 = df2[['competition_id', 'competition_name', 'type', 'gender', 'category_id']]

In [63]:
df2.head()

,competition_id,competition_name,type,gender,category_id
0,sr:competition:620,Hopman Cup,mixed,mixed,sr:category:181
1,sr:competition:660,World Team Cup,mixed,men,sr:category:3
2,sr:competition:990,ATP Challenger Tour Finals,singles,men,sr:category:72
3,sr:competition:1207,Championship International Series,singles,women,sr:category:6
4,sr:competition:2100,Davis Cup,mixed,men,sr:category:76

In [64]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6490 entries, 0 to 6489
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   competition_id    6490 non-null   object
 1   competition_name  6490 non-null   object
 2   type              6490 non-null   object
 3   gender            6490 non-null   object
 4   category_id       6490 non-null   object
dtypes: object(5)
memory usage: 253.6+ KB

In [65]:
df2.duplicated().sum()

0

###  # competitions.csv is perfectly clean and ready for insights

In [66]:
# Save clean file
df2.to_csv('clean_competitions.csv', index=False)

In [67]:
# load the clean competitions.csv

clean_df = pd.read_csv("clean_competitions.csv")
clean_df.head()

,competition_id,competition_name,type,gender,category_id
0,sr:competition:620,Hopman Cup,mixed,mixed,sr:category:181
1,sr:competition:660,World Team Cup,mixed,men,sr:category:3
2,sr:competition:990,ATP Challenger Tour Finals,singles,men,sr:category:72
3,sr:competition:1207,Championship International Series,singles,women,sr:category:6
4,sr:competition:2100,Davis Cup,mixed,men,sr:category:76