In [3]:
# import libraries
import pandas as pd

# Dataset 1 - competitor.csv

In [4]:
# loading csv
df1 = pd.read_csv('competitor.csv')

In [5]:
# first few rows
df1.head()

          competitor_id               name  country country_code abbreviation
0  sr:competitor:407573    Alcaraz, Carlos    Spain          ESP          ALC
1  sr:competitor:225050     Sinner, Jannik    Italy          ITA          SIN
2   sr:competitor:14882    Djokovic, Novak   Serbia          SRB          DJO
3   sr:competitor:57163  Zverev, Alexander  Germany          DEU          ZVE
4  sr:competitor:359602   Musetti, Lorenzo    Italy          ITA          MUS

In [7]:
# rows and columns
df1.shape

(1000, 5)

In [6]:
# Basic information about dataset
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   competitor_id  1000 non-null   object
 1   name           1000 non-null   object
 2   country        1000 non-null   object
 3   country_code   946 non-null    object
 4   abbreviation   1000 non-null   object
dtypes: object(5)
memory usage: 39.2+ KB

In [8]:
# number of columns
df1.columns.tolist()

['competitor_id', 'name', 'country', 'country_code', 'abbreviation']

Total count - 1000
country_code - 54 missing values -> beed to fix

In [9]:
# filling missing values by 'Unknown'
df1['country_code'].fillna('UNK', inplace=True)

C:\Users\Shrey\AppData\Local\Temp\ipykernel_19312\3262064760.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['country_code'].fillna('UNK', inplace=True)

In [10]:
df1.isnull().sum()

competitor_id    0
name             0
country          0
country_code     0
abbreviation     0
dtype: int64

In [11]:
df1.duplicated().sum()

0

In [13]:
# Save clean file
df1.to_csv('clean_competitor.csv', index=False)

In [14]:
# load the csv
clean_df = pd.read_csv("clean_competitor.csv")

In [15]:
clean_df.head()

          competitor_id               name  country country_code abbreviation
0  sr:competitor:407573    Alcaraz, Carlos    Spain          ESP          ALC
1  sr:competitor:225050     Sinner, Jannik    Italy          ITA          SIN
2   sr:competitor:14882    Djokovic, Novak   Serbia          SRB          DJO
3   sr:competitor:57163  Zverev, Alexander  Germany          DEU          ZVE
4  sr:competitor:359602   Musetti, Lorenzo    Italy          ITA          MUS

In [16]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   competitor_id  1000 non-null   object
 1   name           1000 non-null   object
 2   country        1000 non-null   object
 3   country_code   1000 non-null   object
 4   abbreviation   1000 non-null   object
dtypes: object(5)
memory usage: 39.2+ KB

# Dataset 2 - rankings.csv

In [4]:
df2 = pd.read_csv('ranking.csv')

In [5]:
df2.shape

(1000, 5)

In [6]:
df2.head()

   rank  movement  points  competitions_played         competitor_id
0     1         0   13550                   18  sr:competitor:407573
1     2         0   11400                   19  sr:competitor:225050
2     3         0    5370                   18   sr:competitor:14882
3     4         0    4905                   22   sr:competitor:57163
4     5         0    4365                   22  sr:competitor:359602

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   rank                 1000 non-null   int64
 1   movement             1000 non-null   int64
 2   points               1000 non-null   int64
 3   competitions_played  1000 non-null   int64
 4   competitor_id        1000 non-null   object
dtypes: int64(4), object(1)
memory usage: 39.2+ KB

In [8]:
df2.isnull().sum()

rank                   0
movement               0
points                 0
competitions_played    0
competitor_id          0
dtype: int64

In [9]:
df2.duplicated().sum()

0

In [13]:
# save clean ranking
df2.to_csv('clean_ranking.csv', index=False)

In [14]:
# load clean ranking.csv
clean_df = pd.read_csv("clean_ranking.csv")

In [15]:
clean_df.head()

   rank  movement  points  competitions_played         competitor_id
0     1         0   13550                   18  sr:competitor:407573
1     2         0   11400                   19  sr:competitor:225050
2     3         0    5370                   18   sr:competitor:14882
3     4         0    4905                   22   sr:competitor:57163
4     5         0    4365                   22  sr:competitor:359602