In [1]:
# importing libraries
import pandas as pd

# Dataset 1 - complexes.csv

In [2]:
df1 = pd.read_csv("complexes.csv")

In [3]:
# first few rows
df1.head()

        complex_id                           complex_name
0   sr:complex:705                               Nacional
1  sr:complex:1078                     Estadio la Cartuja
2  sr:complex:1495                            Sibur Arena
3  sr:complex:2375             Complexo de Tenis do Jamor
4  sr:complex:4032  Shree Shiv Chhatrapati Sports Complex

In [4]:
# Basic information
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   complex_id    761 non-null    object
 1   complex_name  761 non-null    object
dtypes: object(2)
memory usage: 12.0+ KB

In [5]:
# check missing values
df1.isnull().sum()

complex_id      0
complex_name    0
dtype: int64

In [6]:
# check duplicates
df1.duplicated().sum()

0

### Save clean csv

In [7]:
df1.to_csv('clean_complexes.csv', index=False)

### load the clean complexes

In [8]:
clean_df = pd.read_csv("clean_complexes.csv")

In [9]:
clean_df.head()

        complex_id                           complex_name
0   sr:complex:705                               Nacional
1  sr:complex:1078                     Estadio la Cartuja
2  sr:complex:1495                            Sibur Arena
3  sr:complex:2375             Complexo de Tenis do Jamor
4  sr:complex:4032  Shree Shiv Chhatrapati Sports Complex

#### Data is perfectly clean, no cleaning needed here

# Dataset 2 - venues.csv

In [10]:
df2 = pd.read_csv("venues.csv")

In [11]:
df2.head()

,venue_id,venue_name,city,country,country_code,timezone,complex_id
0,sr:venue:70045,Cancha Central,Santiago,CHILE,CHL,America/Santiago,sr:complex:705
1,sr:venue:74856,Centre Court,Seville,SPAIN,ESP,Europe/Madrid,sr:complex:1078
2,sr:venue:74858,Court One,Seville,SPAIN,ESP,Europe/Madrid,sr:complex:1078
3,sr:venue:62149,Sibur Arena,Saint Petersburg,RUSSIAN FEDERATION,RUS,Europe/Moscow,sr:complex:1495
4,sr:venue:1500,CENTER COURT,Saint Petersburg,RUSSIAN FEDERATION,RUS,Europe/Moscow,sr:complex:1495

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3913 entries, 0 to 3912
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   venue_id      3913 non-null   object
 1   venue_name    3913 non-null   object
 2   city          3913 non-null   object
 3   country       3913 non-null   object
 4   country_code  3913 non-null   object
 5   timezone      3913 non-null   object
 6   complex_id    3913 non-null   object
dtypes: object(7)
memory usage: 214.1+ KB

In [13]:
df2.shape

(3913, 7)

In [14]:
df2.describe()

,venue_id,venue_name,city,country,country_code,timezone,complex_id
count,3913,3913,3913,3913,3913,3913,3913
unique,3913,1081,435,76,76,90,603
top,sr:venue:70045,Court 1,London,UNITED STATES,USA,America/New_York,sr:complex:33222
freq,1,331,49,633,633,324,29

In [16]:
df2.columns.tolist()

['venue_id',
 'venue_name',
 'city',
 'country',
 'country_code',
 'timezone',
 'complex_id']

In [21]:
df2.isnull().sum()

venue_id        0
venue_name      0
city_name       0
country_name    0
country_code    0
timezone        0
complex_id      0
dtype: int64

In [22]:
df2.duplicated().sum()

0

## Data Transformation - fix the column names(different from schema)

In [17]:
df2.rename(columns={
    'city': 'city_name',
    'country': 'country_name'
}, inplace=True)

In [18]:
df2.columns.tolist()

['venue_id',
 'venue_name',
 'city_name',
 'country_name',
 'country_code',
 'timezone',
 'complex_id']

In [23]:
# Save the clean file
df2.to_csv("clean_venues.csv", index = False)

In [24]:
# load the clean venues.csv
clean_df = pd.read_csv("clean_venues.csv")

In [25]:
clean_df.head()

,venue_id,venue_name,city_name,country_name,country_code,timezone,complex_id
0,sr:venue:70045,Cancha Central,Santiago,CHILE,CHL,America/Santiago,sr:complex:705
1,sr:venue:74856,Centre Court,Seville,SPAIN,ESP,Europe/Madrid,sr:complex:1078
2,sr:venue:74858,Court One,Seville,SPAIN,ESP,Europe/Madrid,sr:complex:1078
3,sr:venue:62149,Sibur Arena,Saint Petersburg,RUSSIAN FEDERATION,RUS,Europe/Moscow,sr:complex:1495
4,sr:venue:1500,CENTER COURT,Saint Petersburg,RUSSIAN FEDERATION,RUS,Europe/Moscow,sr:complex:1495

In [26]:
df2.columns.tolist()

['venue_id',
 'venue_name',
 'city_name',
 'country_name',
 'country_code',
 'timezone',
 'complex_id']

#### No nulls and duplicates in the venues.csv. Performed data transformation by fixing the name of columns like city and country. taht means data is now perfectly clean and ready to give business anlysis.